baseURL = "https://Nykenik24.github.io"
languageCode = "en-us"
title = "Nykenik24"
enableGitInfo = true

[[menu.main]]
	name = "<u>H</u>ome"
	url = "/"
	weight = 1

[[menu.main]]
	name = "<u>T</u>ags"
	url = "/tags"
	weight = 3

[params]
	description = "Nykenik24's Website"

[markup.highlight]
	codeFences = true
	style = "catppuccin-mocha"
	lineNumbersInTable = false
	noClasses = false

[markup.goldmark.renderer]
	unsafe = true

[outputs]
	home = [ "html", "rss", "json" ]
	page = [ "html" ]

[[module.imports]]
	path = "github.com/barklan/hugo-dead-simple"
