# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://your_domain.com/"
theme = "congo"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 5

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Homepage"
    pageRef = "/"
    weigth = 10
  [[menu.main]]
    name = "Blog"
    pageRef = "/blog"
    weigth = 20
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/Nykenik24/blog"
    weigth = 40
    [menu.main.params]
      icon = "github"
  [[menu.main]]
    identifier = "search"
    weigth = 99
    [menu.main.params]
      action = "search"
      icon = "magnifying-glass"
