# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://your_domain.com/"
theme = "congo"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 5

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menus]
  # main
  [[menus.main]]
    name = "Homepage"
    pageRef = "/"
    weigth = 10
  [[menus.main]]
    name = "Blog"
    pageRef = "/blog"
    weigth = 20
  [[menus.main]]
    name = "Projects"
    pageRef = "/projects"
    weigth = 30
  [[menus.main]]
    identifier = "github-repo"
    url = "https://github.com/Nykenik24/blog"
    weigth = 40
    [menus.main.params]
      icon = "github"
  [[menus.main]]
    name = "All posts"
    pageRef = "/tags/post"
    weigth = 50
  [[menus.main]]
    identifier = "separator"
    weigth = 99
  # footer
  [[menus.footer]]
    identifier = "github"
    url = "https://github.com/Nykenik24"
    weigth = 10
    [[menus.footer.params]]
      icon = "github"
  [[menus.footer]]
    identifier = "youtube"
    url = "https://youtube.com/@nykenik24"
    weigth = 20
    [[menus.footer.params]]
      icon = "youtube"
  [[menus.footer]]
    name = "blog"
    pageRef = "/blog"
    weigth = 30
  [[menus.footer]]
    name = "projects"
    pageRef = "/projects"
    weigth = 40

