languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Nykenik24"
copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["Blog"]
  # description = "My awesome website"

[params.author]
  name = "Nykenik24"
  # image = "images/author.jpg"
  headline = "Game developer (only as a hobby)."
  bio = "I like making games as a hobby, i develop them in lua with LOVE2D. I am making a dungeon crawler, roguelike game called 'Gauntlet of Ageon'"
  links = [
    { github = "https://github.com/Nykenik24" },
    { youtube = "https://youtube.com/@nykenik24" },
  ]
